#!/bin/sh

destroyScaffoldComponent(){
        rails destroy scaffold $1;
        initDB;
}

destroyGeneratedComponent(){
        rails destoy $1;
        initDB;
}

initDB(){
        rake db:reset
        rake db:drop
        rake db:migrate

}

mvModelFileName(){
        cd app/models/
        for i in `ls | grep ^$1.*.rb$`
        do
                sed -e "s/$1/$2/g" $i
        done
        cd ../..
}

adaptation(){
#mvModelFileName $1 $2;
initDB;
}

adaptation;
